const data = {
    products:[
        {
            _id:"1",
            name:'Air Force1 White',
            category: 'Liftstyle',
            price: '100 $',countInStock:0,
            image:'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/4f37fca8-6bce-43e7-ad07-f57ae3c13142/air-force-1-07-shoe-WrLlWX.png',
            brand:'Nike',
            rating: 3.5,
            numReview:10,
            description:'Hight quality product',
        },
        {
            _id:"2",
            name:'Nike Force1 Gore-text',
            category: 'Liftstyle ',
            price:'200$',countInStock:20,
            image:'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/754ce91c-7b03-4106-8210-bcfd70063bb3/air-force-1-07-lx-shoes-Sx6klF.png',
            brand:'Nike',
            rating: 2.6,
            numReview:9,
            description:'Hight quality product',
        },
        {
            _id:"3",
            name:'Nike Air Max 97',
            category: 'Liftstyle',
            price:'230$',countInStock:30,
            image:'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/5d9f6c0e-5f58-4df3-b4f2-6c2ea7fc30f9/air-max-97-se-shoes-NMMVFJ.png',
            brand:'Nike',
            rating: 4.7,
            numReview:20,
            description:'Hight quality product',
        },
        {
            _id:"4",
            name:'Nike Blazer Low ',
            category: 'Liftstyle',
            price:'220$',countInStock:40,
            image:'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/389b709e-5102-4e55-aa5d-07099b500831/blazer-m_id-77-vintage-shoe-dNWPTj.png',
            brand:'Nike',
            rating: 4.8,
            numReview:15,
            description:'Hight quality product',
        },
        {
            _id:"5",
            name:'Nike NEXT %FLyknit',
            category: 'Running',
            price:'300$',countInStock:10,
            image:'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/91f590d3-a78f-4d84-8019-55b73f94ba88/air-zoom-alphafly-next-flyknit-road-racing-shoe-bbNsmD.png',
            brand:'Nike',
            rating: 4.9,
            numReview:11,
            description:'Hight quality product',
        },
        {
            _id:"6",
            name:'Nike ZoomxDragonFly',
            category: 'Running',
            image:'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/1b57a253-3863-4d2c-b465-53691324bc0a/zoomx-vaporfly-next-2-road-racing-shoe-STlc3F.png',
            price:'220$',countInStock:100,
            brand:'Nike',
            rating: 4.1,
            numReview:12,
            description:'Hight quality product',
        },
        {
            _id:"7",
            name:'Nike React Flynit2',
            category: 'Running',
            price:'120$',countInStock:5,
            image:'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/09998b00-5c8a-4c94-ad75-6ddae10e5f49/zoomx-dragoy-racing-spike-mKMFbB.png',
            brand:'Running',
            rating: 4.0,
            numReview:18,
            description:'Hight quality product',
        },
        {
            _id:'8',
            name:'Nike Zoomx Next 2%',
            category: 'Running',
            price:'310$',countInStock:200,
            image:'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/9efd757c-957c-464e-993b-b0f005ee128b/zoomx-vaporfly-next-2-racing-shoes-D4ntS0.png',
            brand:'Nike',
            rating: 3.5,
            numReview:19,
            description:'Hight quality product',
        },
        {
            _id:'9',
            name:'Nike Zoomx Next 2%',
            category: 'Running',
            price:'310$',countInStock:200,
            image:'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/9efd757c-957c-464e-993b-b0f005ee128b/zoomx-vaporfly-next-2-racing-shoes-D4ntS0.png',
            brand:'Nike',
            rating: 3.5,
            numReview:19,
            description:'Hight quality product',
        },
        
    ]
}
export default data