// const data = {
//     products:[
//         {
//             id:"1",
//             name:'Air Force1 White',
//             category: 'Liftstyle',
//             price: '100 $',
//             image:'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/4f37fca8-6bce-43e7-ad07-f57ae3c13142/air-force-1-07-shoe-WrLlWX.png',
//             brand:'Nike',
//             rating: 3.5,
//             numReview:10,
//             description:'Hight quality product',
//         },
//         {
//             id:"2",
//             name:'Nike Force1 Gore-text',
//             category: 'Liftstyle ',
//             price:'200$',
//             image:'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/adc7cecb-c02a-42c1-b2de-67ddc141295d/air-force-1-gore-tex-shoes-xkl3Ps.png',
//             brand:'Nike',
//             rating: 2.6,
//             numReview:9,
//             description:'Hight quality product',
//         },
//         {
//             id:"3",
//             name:'Nike Air Max 97',
//             category: 'Liftstyle',
//             price:'220$',
//             image:'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/a02b46e1-e2fd-4fd5-b326-01147d09c3a3/air-max-97-se-shoes-wJcltf.png',
//             brand:'Nike',
//             rating: 4.7,
//             numReview:20,
//             description:'Hight quality product',
//         },
//         {
//             id:"4",
//             name:'Nike Blazer Low ',
//             category: 'Liftstyle',
//             price:'220$',
//             image:'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/4d87680e-a278-47e8-b0d4-d6e76f924c4d/blazer-low-77-prm-shoe-pnHzBj.png',
//             brand:'Nike',
//             rating: 4.8,
//             numReview:15,
//             description:'Hight quality product',
//         },
//         {
//             id:"5",
//             name:'Nike NEXT %FLyknit',
//             category: 'Running',
//             price:'300$',
//             image:'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/91f590d3-a78f-4d84-8019-55b73f94ba88/air-zoom-alphafly-next-flyknit-road-racing-shoe-bbNsmD.png',
//             brand:'Nike',
//             rating: 4.9,
//             numReview:11,
//             description:'Hight quality product',
//         },
//         {
//             id:"6",
//             name:'Nike ZoomxDragonFly',
//             category: 'Running',
//             image:'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/09998b00-5c8a-4c94-ad75-6ddae10e5f49/zoomx-dragoy-racing-spike-mKMFbB.png',
//             price:'220$',
//             brand:'Nike',
//             rating: 4.1,
//             numReview:12,
//             description:'Hight quality product',
//         },
//         {
//             id:"7",
//             name:'Nike React Flynit2',
//             category: 'Running',
//             price:'120$',
//             image:'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/501868bd-7fcb-4063-b3b2-d8e360b0993e/react-infinity-run-flyknit-2-running-shoes-9hhcGc.png',
//             brand:'Running',
//             rating: 4.0,
//             numReview:18,
//             description:'Hight quality product',
//         },
//         {
//             id:'8',
//             name:'Nike Zoomx Next 2%',
//             category: 'Running',
//             price:'310$',
//             image:'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/fa0a8a53-654d-41fc-99c8-d094aae16cb5/zoomx-vaporfly-next-2-racing-shoes-fG92S8.png',
//             brand:'Nike',
//             rating: 3.5,
//             numReview:19,
//             description:'Hight quality product',
//         },
        
//     ]
// }
// export default data